//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOdaDemirba
    {
        public int odaDemirbasId { get; set; }
        public int odaId { get; set; }
        public int demirbaslarId { get; set; }
        public int adet { get; set; }
    
        public virtual tblOda tblOda { get; set; }
    }
}
