//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOda()
        {
            this.tblOdaDemirbas = new HashSet<tblOdaDemirba>();
        }
    
        public int odaId { get; set; }
        public string odaAdi { get; set; }
        public int personelId { get; set; }
        public int fakulteId { get; set; }
    
        public virtual tblFakulte tblFakulte { get; set; }
        public virtual tblPersonel tblPersonel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOdaDemirba> tblOdaDemirbas { get; set; }
    }
}
